language: java
jdk: oraclejdk8
install: true
cache:
  directories:
    - $HOME/.m2
before_install:
  - chmod +x run.sh
script:
  - mvn clean install
  - mvn failsafe:integration-test
  - ./run.sh example/market.csv -l -a 1000
